mkdir "e:\desk\C”Ô—‘\CÃ‚ø‚\c_file"
move "e:\desk\C”Ô—‘\CÃ‚ø‚\*.c" "e:\desk\C”Ô—‘\CÃ‚ø‚\c_file" 
del "e:\desk\C”Ô—‘\CÃ‚ø‚\*.*"
move "e:\desk\C”Ô—‘\CÃ‚ø‚\c_file\*.c" "e:\desk\C”Ô—‘\CÃ‚ø‚\"
del "e:\desk\C”Ô—‘\CÃ‚ø‚\c_file"

mkdir "e:\desk\C”Ô—‘\Cprimerplus\c_file"
move "e:\desk\C”Ô—‘\Cprimerplus\*.c" "e:\desk\C”Ô—‘\Cprimerplus\c_file" 
del "e:\desk\C”Ô—‘\Cprimerplus\*.*"
move "e:\desk\C”Ô—‘\Cprimerplus\c_file\*.c" "e:\desk\C”Ô—‘\Cprimerplus\"
del "e:\desk\C”Ô—‘\Cprimerplus\c_file"

mkdir "e:\desk\C”Ô—‘\¡∑ ÷\c_file"
move "e:\desk\C”Ô—‘\¡∑ ÷\*.c" "e:\desk\C”Ô—‘\¡∑ ÷\c_file" 
del "e:\desk\C”Ô—‘\¡∑ ÷\*.*"
move "e:\desk\C”Ô—‘\¡∑ ÷\c_file\*.c" "e:\desk\C”Ô—‘\¡∑ ÷\"
del "e:\desk\C”Ô—‘\¡∑ ÷\c_file"